services:
  # Flask Backend Service
  - type: web
    name: cleansweep-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false

  # Streamlit Frontend Service
  - type: web
    name: cleansweep-frontend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && streamlit run streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: BACKEND_URL
        value: https://cleansweep-backend.onrender.com 