services:
  # Flask Backend Service
  - type: web
    name: cleansweep-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py

  # Telegram Bot Service
  - type: worker
    name: cleansweep-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false 
